pipelines:
  resume-resources:
    group: first
    label_template: ${COUNT}
    lock_behavior: lockOnFailure
    materials:
      git:
        git: https://github.com/adityasood/licensemgmt.git
        shallow_clone: true
        auto_update: true
        branch: master
    stages:
    - resume-resources:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          resume-resources:
            timeout: 1
            tasks:
            - exec:
                command: bash
                arguments: ./resume_resources.sh deepti
                run_if: failed
