pipelines:
  resume-resources:
    group: test
    materials:
      git: git@<git_url>
      branch: master
    stages:
      - resume-resources: # name of stage
          jobs:
            resume-resources: # name of the job
              tasks:
                - exec: # indicates type of task
                    command: bash
                    arguments: ./resume_resources.sh deepti