pipelines:
  yamlpipe123:
    group: simple
    materials:
      mygit1:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/adityasood/licensemgmt.git
    stages:
      - build: # name of stage
          jobs:
            build: # name of the job
              tasks:
               - script: "echo -e 'this is the\nBestUse of\nOurplugin'>testFile.txt"
